### ISSUE TITLE
Rapport : documentation prévue dans le cahier des charges

### ISSUE THREAD

**Issue by dosseggegw1** [HEIGVD-PRO-A-07/HEIGVD-PRO-A-07-Documentation#13]
- [ ] doc utilisateur = manuel utilisation
Les images doivent être mis à jour + adaptation de ce qui a été implémenté ou non

- [ ] conception technique (à créer)

**Comment by CassandreWoj** [comment]
Doc utilisateur = manuel d'utilisation -> déjà fait à 90%

**Comment by dosseggegw1** [comment]
Merci de compléter la partie

**Comment by g-roch** [comment]
Move to HEIGVD-PRO-A-07/HEIGVD-PRO-A-07#86
