### ISSUE TITLE
Rapport : Organisation du code

### ISSUE THREAD

**Issue by dosseggegw1** [HEIGVD-PRO-A-07/HEIGVD-PRO-A-07-Documentation#14]
Rapport de 2 pages 
- [ ] arborescence du code
- [ ] contenus du code

**Comment by dosseggegw1** [comment]
Avec Cassandre on va rédiger un maximum. Mais il faudra par la suite que les personnes ayant touchés au code complète !

**Comment by g-roch** [comment]
Move to HEIGVD-PRO-A-07/HEIGVD-PRO-A-07#87
