### ISSUE TITLE
Script pour remplir l'AD

### ISSUE THREAD

**Issue by dosseggegw1** [HEIGVD-PRO-A-07/HEIGVD-PRO-A-07-Documentation#20]
Pour facilité la partie installation / test, il serait bien d'avoir un script pour générer des utilisateurs et leur assigné un des groupes : élèves / professeurs. 

Ce script sera ajouté en référence dans le Guide d'installation.

**Comment by g-roch** [comment]
Move to HEIGVD-PRO-A-07/HEIGVD-PRO-A-07#89
