### ISSUE TITLE
Rendu final : Journal de travail

### ISSUE THREAD

**Issue by dosseggegw1** [HEIGVD-PRO-A-07/HEIGVD-PRO-A-07-Documentation#8]
Mettre à jour son journal de travail (version finale)
- [ ] Gabriel Roch
- [ ] Gwendoline Dössegger
- [ ] Cassandre Wojciechowski
- [ ] Laurent Thoeny
- [ ] Laurent Scherer
- [ ] Nenad Rajic

**Comment by g-roch** [comment]
Move to HEIGVD-PRO-A-07/HEIGVD-PRO-A-07#81
