### ISSUE TITLE
Rendu final : Présentation

### ISSUE THREAD

**Issue by dosseggegw1** [HEIGVD-PRO-A-07/HEIGVD-PRO-A-07-Documentation#9]
La présentation contiendra les points suivants :
- [ ] Rappel et couverture des objectifs (3')
- [ ] Démonstration (10')
- [ ] Forces et faiblesses du logiciel (3')
- [ ] "Lessons learned (3')
- [ ] Questions (6')

**Comment by g-roch** [comment]
Move to HEIGVD-PRO-A-07/HEIGVD-PRO-A-07#82
